name: Run Python script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./csv_seeder

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Gradio
        run: python -m pip install gradio

      - name: Log in to Hugging Face
        run: |
          python -c 'import huggingface_hub; huggingface_hub.login(token="${{ secrets.hf_token }}")'
          echo "Logged into Hugging Face"

      - name: Verify Login (Optional)
        run: |
          python -c 'import huggingface_hub; print(huggingface_hub.whoami())'

      - name: Deploy to Spaces
        run: gradio deploy --token ${{ secrets.hf_token }}
