name: Run Python script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./csv_seeder

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Gradio
        run: python -m pip install gradio

      - name: Configure Git Credential Helper
        run: git config --global credential.helper store

      - name: Log in and Deploy to Hugging Face Spaces
        run: |
          python -c 'import huggingface_hub; huggingface_hub.login(token="${{ secrets.hf_token }}", add_to_git_credential=True)'
          echo "Logged into Hugging Face"
          gradio deploy
